[package]
name = "ssg"
version = "0.1.0"
authors = ["Kevin Nobel <kevin@2sk.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
